/**
 * Storybook Main Configuration
 * Generated by Storybook System (Adaptive Webpack Generator)
 */
const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
  stories: [
    '../stories/**/*.stories.@(js|jsx|ts|tsx|mdx)',
    '../src/**/*.stories.@(js|jsx|ts|tsx|mdx)'
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions'
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {}
  },
  docs: {
    autodocs: 'tag',
  },
  webpackFinal: async (config) => {
    // Base extensions supported by default
    config.resolve.extensions = [
      '.js', '.jsx', '.ts', '.tsx', '.json', '.css', '.scss', '.sass'
    ];
    
    
    // React-specific configuration
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      use: [
        {
          loader: require.resolve('babel-loader'),
          options: {
            presets: [
              ['react-app', { flow: false, typescript: true }]
            ]
          }
        }
      ]
    });
    
    // Add TSConfig paths support
    if (config.resolve.plugins) {
      config.resolve.plugins.push(new TsconfigPathsPlugin({
        configFile: path.resolve(__dirname, '../tsconfig.json'),
      }));
    } else {
      config.resolve.plugins = [new TsconfigPathsPlugin({
        configFile: path.resolve(__dirname, '../tsconfig.json'),
      })];
    }
    return config;
  }
};